# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - '5173:5173'
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules: {}
